/* What: the dryer's plant for the host tests — the two PTC heaters, their outlet NTCs and the
 * chamber, as a model fitted to the heater runs measured on the unit on 2026-09-13
 * (the heater-2026-09-13 data set; the parameters in thermal_params.h, generated by
 * tools/thermal_fit.py).  Test code only: floats are allowed here, never in src/.
 * How: per side s (0 left, 1 right), with u = duty / 100 and C the chamber,
 *     dP_s/dt = a_s * u * (1 + x_s * min(P_s - C, D_MAX)) - k_s * (P_s - C)
 *     dN_s/dt = (P_s - N_s) / tau_s
 *     dC/dt   = h * ((N_0 + N_1) / 2 - C) - m * (C - ambient)
 * integrated by Euler in steps of at most 10 ms (the firmware's tick).  P is the heater and its
 * heatsink, N the outlet NTC the firmware reads.  The heater's power grows with its temperature
 * over the measured range and is held beyond it (D_MAX), so nothing is extrapolated.
 * The chamber's loss to the room m is assumed, not fitted (the runs are too short for it to
 * show); it is the field chamber_m of each instance, set by fake_thermal_init() from
 * thermal_params.h — tests may override it after init by assigning the field.
 * A fan that is off is a SYNTHETIC variant, never measured — by rule the unit is never heated
 * with a fan stopped: its side's cooling k_s and its share of the chamber's feed are multiplied by
 * FAKE_THERMAL_NOFAN_FACTOR, enough for the dryer's tests to show that its protections see a
 * stopped fan, and nothing more.  No test may read a physical claim into that variant.
 * Depends on: <stdint.h>, thermal_params.h.  Header-only (static inline), like fake_field.h:
 * the host build links the core and one test file, nothing else. */
#ifndef ACE2K_TEST_FAKE_THERMAL_H
#define ACE2K_TEST_FAKE_THERMAL_H
#include <stdint.h>
#include "thermal_params.h"

#define FAKE_THERMAL_STEP_MS      10U
#define FAKE_THERMAL_NOFAN_FACTOR 0.2 /* synthetic: see the header comment */
#define FAKE_THERMAL_FANS_BOTH    3U  /* fan_mask: bit 0 left, bit 1 right */

// NOLINTNEXTLINE(readability-identifier-naming)
struct fake_thermal {
    double p[2]; /* the heaters, degC */
    double n[2]; /* the outlet NTCs, degC */
    double c;    /* the chamber, degC */
    double ambient;
    double chamber_m; /* the chamber's loss to the room, 1/s: assumed, not fitted; tests may
                         override */
};

/* Every node at the ambient: a unit at rest in its room. */
static inline void fake_thermal_init(struct fake_thermal *m, int32_t ambient_mc)
{
    m->ambient = (double)ambient_mc / 1000.0;
    m->p[0] = m->p[1] = m->n[0] = m->n[1] = m->c = m->ambient;
    m->chamber_m = THERMAL_CHAMBER_M;
}

/* Each heater at its NTC's reading, the chamber at its own: the start of a replayed run. */
static inline void fake_thermal_set(struct fake_thermal *m, int32_t left_mc, int32_t right_mc,
                                    int32_t chamber_mc)
{
    m->p[0] = m->n[0] = (double)left_mc / 1000.0;
    m->p[1] = m->n[1] = (double)right_mc / 1000.0;
    m->c = (double)chamber_mc / 1000.0;
}

static inline void fake_thermal_substep(struct fake_thermal *m, double u, unsigned fan_mask,
                                        double dt_s)
{
    static const double a[2] = { THERMAL_LEFT_A, THERMAL_RIGHT_A };
    static const double k[2] = { THERMAL_LEFT_K, THERMAL_RIGHT_K };
    static const double tau[2] = { THERMAL_LEFT_TAU, THERMAL_RIGHT_TAU };
    static const double x[2] = { THERMAL_LEFT_X, THERMAL_RIGHT_X };
    double dp[2];
    double dn[2];
    double feed = 0.0;
    for (unsigned s = 0; s < 2U; s++) {
        double cool = ((fan_mask >> s) & 1U) != 0U ? 1.0 : FAKE_THERMAL_NOFAN_FACTOR;
        double d = m->p[s] - m->c;
        double dc = d < THERMAL_D_MAX ? d : THERMAL_D_MAX;
        dp[s] = (a[s] * u * (1.0 + (x[s] * dc))) - (k[s] * cool * d);
        dn[s] = (m->p[s] - m->n[s]) / tau[s];
        feed += 0.5 * cool * (m->n[s] - m->c);
    }
    double dcham = (THERMAL_CHAMBER_H * feed) - (m->chamber_m * (m->c - m->ambient));
    for (unsigned s = 0; s < 2U; s++) {
        m->p[s] += dp[s] * dt_s;
        m->n[s] += dn[s] * dt_s;
    }
    m->c += dcham * dt_s;
}

/* Advances the model by dt_ms at a firing duty of duty_pct (0–100, the half-cycles fired over
 * the interval) with the fans of fan_mask on. */
static inline void fake_thermal_step(struct fake_thermal *m, unsigned duty_pct, unsigned fan_mask,
                                     unsigned dt_ms)
{
    double u = (double)duty_pct / 100.0;
    while (dt_ms > 0U) {
        unsigned h = dt_ms < FAKE_THERMAL_STEP_MS ? dt_ms : FAKE_THERMAL_STEP_MS;
        fake_thermal_substep(m, u, fan_mask, (double)h / 1000.0);
        dt_ms -= h;
    }
}

static inline int32_t fake_thermal_mc(double c)
{
    return (int32_t)((c * 1000.0) + (c >= 0.0 ? 0.5 : -0.5));
}

/* side 0 left, 1 right. */
static inline int32_t fake_thermal_ntc_mc(const struct fake_thermal *m, unsigned side)
{
    return fake_thermal_mc(m->n[side]);
}

static inline int32_t fake_thermal_heater_mc(const struct fake_thermal *m, unsigned side)
{
    return fake_thermal_mc(m->p[side]);
}

static inline int32_t fake_thermal_chamber_mc(const struct fake_thermal *m)
{
    return fake_thermal_mc(m->c);
}

/* A room of a different temperature (the tests' 15 and 42 degC cases). */
static inline void fake_thermal_set_ambient(struct fake_thermal *m, int32_t ambient_mc)
{
    m->ambient = (double)ambient_mc / 1000.0;
}

#endif
