/* Generated by tools/thermal_fit.py, do not edit.  The dryer's thermal model fitted to
 * the heater runs of
 *   tests/data/heater-2026-09-13
 *   tests/data/dryer-b2
 * (tests/fake_thermal.h has the equations).
 * Units: a in degC/s at full duty, k in 1/s, tau in s, x in 1/degC, D_MAX in degC,
 * h and m in 1/s, ambient in degC.  m is assumed, not fitted (tools/thermal_fit.py). */
#ifndef ACE2K_TEST_THERMAL_PARAMS_H
#define ACE2K_TEST_THERMAL_PARAMS_H
// clang-format off
// NOLINTBEGIN
#define THERMAL_LEFT_A   0.667506
#define THERMAL_LEFT_K   0.032390
#define THERMAL_LEFT_TAU 13.198449
#define THERMAL_LEFT_X   0.157527
#define THERMAL_RIGHT_A   1.408789
#define THERMAL_RIGHT_K   0.046953
#define THERMAL_RIGHT_TAU 15.836685
#define THERMAL_RIGHT_X   0.084804
#define THERMAL_D_MAX 37.0
#define THERMAL_CHAMBER_H 0.003603
#define THERMAL_CHAMBER_M 0.000841
#define THERMAL_BENCH_AMBIENT_C 24.280000
#define THERMAL_RISE_MAX_MC_S_PER_PCT 35 /* copied into dryer.h by hand */
// NOLINTEND
// clang-format on
#endif
