#!/usr/bin/env python3
"""Generate src/ace2k/env/env_table.h: the outlet NTC's millivolts → millidegrees table.

Divider: 100 kΩ pull-up to 3.3 V, the NTC to ground (docs/hardware.md "Analogue inputs");
NTC: 100 kΩ at 25 °C, B = 3950.  One entry every 25 mV from 100 to 3200 mV (125 entries);
env.c interpolates linearly between entries (worst error ≈ 0.3 °C at the hot end).

    ntc_table.py OUT            write the header
    ntc_table.py --check OUT    exit 1 if OUT differs from what would be written
"""

import math
import sys

R25, BETA, T25_K, PULLUP, VREF_MV = 100000.0, 3950.0, 298.15, 100000.0, 3300.0
MIN_MV, MAX_MV, STEP_MV = 100, 3200, 25


def millidegrees(mv: int) -> int:
    r = PULLUP * mv / (VREF_MV - mv)
    t = 1.0 / (1.0 / T25_K + math.log(r / R25) / BETA) - 273.15
    return round(t * 1000)


COLUMN_LIMIT, INDENT = 100, 4  # src/ace2k/.clang-format


def column_sizes(items: list) -> list:
    """The column widths (comma included) clang-format gives a long braced list: as many columns
    as fit the column limit, each as wide as its widest item, the fewest lines and, on a tie,
    the fewest columns.  Rendering the table the same way keeps the committed header identical
    to what `make format` would write, so --check and format-check agree."""
    widths = [len(v) + 1 for v in items]  # the item and its comma
    best = None
    for columns in range(1, COLUMN_LIMIT // 3 + 1):
        by_column = [widths[i::columns] for i in range(columns)]
        sizes = [max(w) for w in by_column]
        lines = -(-len(items) // columns)
        if any(max(w) - min(w) > 10 for w in by_column[:-1]):
            continue  # clang-format refuses a column with that much padding
        if sum(sizes) + columns - 1 > COLUMN_LIMIT - INDENT:
            continue
        if best is None or lines < best[0]:
            best = (lines, sizes)
    return best[1]


def render() -> str:
    items = [str(millidegrees(mv)) for mv in range(MIN_MV, MAX_MV + 1, STEP_MV)]
    sizes = column_sizes(items)
    rows = []
    for i in range(0, len(items), len(sizes)):
        row = items[i : i + len(sizes)]
        cells = [f"{v},".ljust(w) for v, w in zip(row[:-1], sizes)]
        rows.append(" " * INDENT + " ".join([*cells, f"{row[-1]},"]))
    body = "\n".join(rows)
    return (
        "/* Generated by tools/ntc_table.py — do not edit.  Millidegrees Celsius of the outlet\n"
        " * NTC for every 25 mV from 100 to 3200 mV (100 kΩ / B 3950, 100 kΩ pull-up to 3.3 V).\n"
        " * Depends on: <stdint.h>. */\n"
        "#ifndef ACE2K_ENV_TABLE_H\n"
        "#define ACE2K_ENV_TABLE_H\n"
        "#include <stdint.h>\n\n"
        f"#define ACE2K_ENV_NTC_TABLE_MIN_MV  {MIN_MV}U\n"
        f"#define ACE2K_ENV_NTC_TABLE_MAX_MV  {MAX_MV}U\n"
        f"#define ACE2K_ENV_NTC_TABLE_STEP_MV {STEP_MV}U\n"
        f"#define ACE2K_ENV_NTC_TABLE_LEN     {len(items)}U\n\n"
        "static const int32_t ace2k_env_ntc_table_mc[ACE2K_ENV_NTC_TABLE_LEN] = {\n"
        f"{body}\n"
        "};\n\n"
        "#endif\n"
    )


def main() -> None:
    check = "--check" in sys.argv
    args = [a for a in sys.argv[1:] if a != "--check"]
    if len(args) != 1:
        sys.exit(__doc__)
    text = render()
    if check:
        with open(args[0], encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print(f"ntc_table: {args[0]} is out of date; regenerate it", file=sys.stderr)
            sys.exit(1)
        print(f"ntc_table: {args[0]} is current")
        return
    with open(args[0], "w", encoding="utf-8") as f:
        f.write(text)
    print(f"ntc_table: wrote {args[0]}")


if __name__ == "__main__":
    main()
